kind: Deployment
apiVersion: apps/v1
metadata:
  name: zeppelin-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zeppelin-server
  template:
    spec:
      containers:
        - name: zeppelin-server
          volumeMounts:
            # configure this to persist notebook
            - name: zeppelin-server-notebook
              mountPath: /opt/zeppelin/notebook
            # configure this to persist Zeppelin configuration
            # - name: zeppelin-server-conf
            #   mountPath: /opt/zeppelin/conf
      volumes:
        - name: zeppelin-server-notebook
          persistentVolumeClaim:
            claimName: zeppelin-notebook-pvc
        # - name: zeppelin-server-conf
        #   persistentVolumeClaim:
        #     claimName: zeppelin-conf-pvc
