kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zeppelin-notebook-pvc
spec:
  storageClassName: hostpath # provided by docker desktop, must be the same as PersistentVolume
  selector:
    matchLabels:
      pv-label: zeppelin-notebook
  accessModes:
    - ReadWriteMany # must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: zeppelin-conf-pvc
# spec:
#   storageClassName: hostpath # provided by docker desktop, must be the same as PersistentVolume
#   selector:
#     matchLabels:
#       pv-label: zeppelin-conf
#   accessModes:
#     - ReadWriteMany # must be the same as PersistentVolume
#   resources:
#     requests:
#       storage: 1Gi

# ---
