kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    spec:
      containers:
      - name: keycloak
        volumeMounts:
          - mountPath: /opt/keycloak/conf/keycloak.conf
            subPath: keycloak.conf
            name: keycloak-conf
      volumes:
        - name: keycloak-conf
          configMap:
            name: keycloak-conf-map
            items:
            - key: keycloak.conf
              path: keycloak.conf